name: online_hunt_news
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  badges: ^3.1.2
  cached_network_image: ^3.0.0
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.3
  dots_indicator: ^4.0.1
  easy_localization: ^3.0.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.1
  flutter_web_browser: ^0.17.3
  flutter_html: ^3.0.0
  flutter_widget_from_html: ^0.17.1
  google_fonts: ^6.3.1
  google_sign_in: ^7.1.1
  # geolocator: ^8.0.1
  # geocoder: ^0.2.1
  html: ^0.15.0
  html_unescape: ^2.0.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  introduction_screen: ^4.0.0
  # launch_review: ^3.0.1
  line_icons: ^2.0.1
  lottie: ^3.0.0
  # location: ^4.3.0
  # package_info: ^2.0.2
  package_info_plus: ^9.0.0
  path_provider: ^2.0.2
  provider: ^6.0.1
  permission_handler: ^12.0.1
  # share: ^2.0.4
  share_plus: ^12.0.0
  shared_preferences: ^2.0.6
  skeleton_text: ^3.0.0
  fluttertoast: ^9.0.0
  url_launcher: ^6.0.9
  youtube_player_flutter: ^9.1.2
  # youtube_plyr_iframe: ^2.0.7
  rounded_loading_button: ^2.0.5
  firebase_analytics: ^12.0.1
  flutter_facebook_auth: ^7.1.2
  the_apple_sign_in: ^1.1.1
  video_player: ^2.1.10
  flick_video_player: ^0.9.0
  # webfeed: ^0.7.0
  # firebase_dynamic_links: ^6.1.10
  # flutter_language_identification: ^0.1.0
  metadata_fetch: ^0.4.1
  flutter_spinkit: ^5.1.0
  crypto: ^3.0.1
  # gallery_saver: ^2.3.2
  uuid: ^4.5.1
  dio: ^5.9.0
  video_thumbnail: ^0.5.6
  file_picker: 
  # chewie: ^1.3.5
  chewie: 
  path: ^1.8.2
  fk_user_agent: ^2.1.0
  # flutter_user_agent:
  #   git:
  #     url: https://github.com/j0j00/flutter_user_agent.git
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  md2_tab_indicator:
    git:
      url: https://github.com/westdabestdb/md2_tab_indicator
      
  google_mobile_ads: ^6.0.0
  facebook_audience_network: ^1.0.0-nullsafety.0

# https://github.com/j0j00/flutter_user_agent.git
  


  audio_session: any
  # cloud_firestore_web: any
  # firebase_analytics_web: any
  # firebase_auth_web: any
  # firebase_core_web: any
  # firebase_messaging_web: any
  # firebase_storage_web: any
  # # flutter_facebook_auth_web: any
  # google_sign_in_web: any
  # image_picker_for_web: any
  # just_audio_web: any
  # shared_preferences_web: any
  # url_launcher_web: any
  # video_player_web: any
  # wakelock_web: any
  # flutter_web_plugins: any
  # fk_user_agent: any
  # webfeed: any
  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"



# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation_files/
    - assets/translations/
    - assets/cities/

  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500

    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900

    - family: Karma
      fonts:
        - asset: assets/fonts/Karma-Regular.ttf
          weight: 400
        - asset: assets/fonts/Karma-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Karma-Medium.ttf
          weight: 600
        - asset: assets/fonts/Karma-Bold.ttf
          weight: 700
        - asset: assets/fonts/Karma-Light.ttf
          weight: 900

    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSerif-Bold.ttf
          weight: 700