// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:online_hunt_news/models/Hive/pdf_timer.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PDFItemModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PDFItemModelAdapter());
  }
}
